name: Node.js Package

on:
  push:
    branches:
      - master
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        name: production-files
        path: ./build
